#!/bin/sh -e
. ../common.sh
. ../common-watch.sh

if [ "$(get_forcestate)" == "drone" ]; then
	logmessage "Forced into Drone State by configuration"
	echo drone
elif [ -s $gwiptbl ] || [ "$(cat /tmp/boot_runs_$interface)" -ge 5 ]; then
	logmessage "Entering connection testing mode"
	echo testing
else
	boot_runs="$(cat /tmp/boot_runs_$interface)"
	boot_runs_new=`expr $boot_runs + 1`
	echo $boot_runs_new > /tmp/boot_runs_$interface
	logmessage "Waiting for p2p table data"
	echo boot
fi
