#!/bin/sh -ex
. ../common.sh
. ../common-watch.sh

DHCPLeaseTime=$(get_fsmsetting net_dhcpleasetime)

#Check if our current Oct3 is valid
CurrentOct3=$(current_oct3)
[ -n "$CurrentOct3" ]

# if our GW IP has been taken we must no use it again
if ! we_own_our_ip; then
    if ! cloud_is_online; then
		logmessage "We dont own our IP & cloud offline -> Robinson state"
		echo robinson
    else
		logmessage "We dont own our IP & cloud online -> Drone state"
		echo drone
    fi
    exit
fi

if test_connectivity $interface internet; then
	logmessage "Internet connection available, checking queen mode"
	return_state="$(return_queenstate)"
	if [ -n "$return_state" ]; then
		echo $return_state
		exit
	fi
fi

if [ "$SO" == "ghost" ]; then
    GhostTime=$(($(date +%s) - $(cat /tmp/ghost_since_$interface)))
else
    GhostTime=0
fi
if ! cloud_is_online; then
	logmessage "No gateways found -> Robinson State"
    echo robinson
elif [ $GhostTime -ge $DHCPLeaseTime ]; then
	logmessage "Ghost Time exceeded DHCP Lease Time & cloud has gateways -> Drone State"
    echo drone
else
	logmessage "Ghost Time below DHCP Lease Time & cloud has gateways -> Ghost State"
    echo ghost
fi
