#!/bin/sh -e
. ../common.sh
. ../common-watcher.sh

#Check if our current Oct3 is valid
CurrentOct3=$(current_oct3)
[ -n "$CurrentOct3" ]

# if our GW IP has been taken we must no use it again
if ! we_own_our_ip; then
	logmessage "We dont own our IP!"
    if ! cloud_is_online; then
	echo robinson
    else
	echo drone
    fi
    exit
fi

if test_connectivity internet; then
	logmessage "Internet connection available, checking queen mode"
	return_queenmode
    exit
fi

if [ "$SO" == "ghost" ]; then
    GhostTime=$(($(date +%s) - $(cat /tmp/ghost_since_$interface)))
else
    GhostTime=0
fi
if ! cloud_is_online; then
	logmessage "No gateways found -> Robinson State"
    echo robinson
elif [ $GhostTime -ge $DHCPLeaseTime ]; then
	logmessage "Ghost Time exceeded DHCP Lease Time & cloud has gateways -> Drone State"
    echo drone
else
	logmessage "Ghost Time below DHCP Lease Time & cloud has gateways -> Ghost State"
    echo ghost
fi
